import './globals.css'
import Link from 'next/link';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={'flex'}>
      <nav className={'flex-auto w-10'}>
        <h3>Demos</h3>
        <ul>
          <li><Link href={'rscdemos/serverfirst'}>SSC to RSC Demo</Link></li>
          <li></li>
          <li>Three</li>
        </ul>
      </nav>
      <main className={'flex-auto w-90'}>

        {children}
      </main>
      </body>
    </html>
  )
}
